---
title: "Critter Game - Data - Catch Trial"
author: "Lauren Oey"
date: "7/7/2017"
output: github_document
---

```{r preamble, tidy=TRUE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(data.table)
#library(xtable)


#setting the directory
setwd("../../mturk/game-1/")


catch_trial_data <- read.csv("game-1-catch_trials.csv")

#View(catch_trial_data)

str(catch_trial_data)
summary(catch_trial_data)

```

# Adjusting Dataframe
```{r}
#attach(catch_trial_data)
catch_trial_data$question_name <- as.factor(ifelse(catch_trial_data$question=="tar1", "tail", "head"))
catch_trial_data$tar1_logic <- as.logical(catch_trial_data$tar1)
catch_trial_data$tar2_logic <- as.logical(catch_trial_data$tar2)
catch_trial_data$trial_num <- as.factor(catch_trial_data$trial_num)
catch_trial_data$workerid <- as.factor(catch_trial_data$workerid)
catch_trial_data$response_logic <- ifelse(catch_trial_data$response=="Yes", TRUE, FALSE)
catch_trial_data$Correct <- ifelse(catch_trial_data$question_name=="tail", ifelse(catch_trial_data$tar1_logic==catch_trial_data$response_logic, TRUE, FALSE), ifelse(catch_trial_data$tar2_logic==catch_trial_data$response_logic, TRUE, FALSE))


  

```

# Proportion Correct By Subject

```{r, results='asis'}
catch_trial_data_by_subj <- catch_trial_data %>%
  group_by(workerid, trial_num, condition) %>%
  distinct() %>%
  summarise(Total = 1, Correct_trial = ifelse(Correct==TRUE, 1, 0)) %>%
  group_by(workerid, condition) %>%
  summarise(Total_trials = sum(Total), Correct_trials = sum(Correct_trial)) %>%
  mutate(Percentage_correct = Correct_trials/Total_trials) %>%
  select(workerid, Percentage_correct, condition)

#catch_trial_data_by_subj

#xt <- xtable(catch_trial_data_by_subj, type="html", caption = "Percentage of correct catch trials per subject.", label = "catch_trial_data_by_subj")
#names(xt) <- c('Subject', 'Percentage of Correct Trials')
#print(xt, comment=FALSE)

Condition_lab <- c(
  pepsin_detector = 'Pepsin Detector',
  label_book = 'Label Book')

graph_by_subj <- ggplot(catch_trial_data_by_subj, aes(x=workerid, y=Percentage_correct, colour=condition, fill=condition)) +
  geom_bar(stat="identity") +
  scale_x_discrete("Subject Number") +
  scale_y_continuous("Percentage of Trials Correct") +
  scale_colour_discrete(guide=guide_legend("Condition"), labels=Condition_lab) +
  scale_fill_discrete(guide=guide_legend("Condition"), labels=Condition_lab) +
  ggtitle("Accuracy on Catch Trials by Subject") +
  theme_minimal()
graph_by_subj


```





