---
title: "Cultural Ratchet Data Exploration"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(reshape2)
library(purrr)
library(jsonlite)
library(tidyr) 
library(dplyr)
library(tidyboot)
library(ggplot2)
library(scales)
library(stringr)
library(digest)
library(ggthemes)
library(forcats)
library(ggalt)
library(grid)
library(cowplot)
```


# Load Concept Summary
```{r}
concept_summary_fp <- c("../../../experiments/mp-game-6/stimuli/fifty_rules/concept_summary.json")
concept_summary <- do.call(rbind.data.frame, jsonlite::fromJSON(concept_summary_fp)) %>%
  mutate(chance_rate= p_test_belongs_to_concept*p_test_belongs_to_concept + (1 -p_test_belongs_to_concept) * (1-p_test_belongs_to_concept))
```

# Complete Games
```{r}
# Load Test Trial Responses
temp <- list.files(
  "../../../data/mp-game-6/complete_games/logTest",
  pattern="*.csv",
  full.names=TRUE
)
test_complete_games <- do.call(rbind, lapply(temp, read.csv, sep=""))

# Load Test Summary Stats
temp <- list.files(
    "../../../data/mp-game-6/complete_games/logScores",
  pattern="*.csv",
  full.names=TRUE
)
scores_complete_games <- do.call(rbind, lapply(temp, read.csv, sep=""))


# Load Time Data
temp <- list.files(
    "../../../data/mp-game-6/complete_games/logTimes",
  pattern="*.csv",
  full.names=TRUE
)
time_complete_games <-do.call(rbind, lapply(temp, readr::read_tsv)) %>%
  group_by(gameid)
```

## Distribution of Complete Data
```{r}
num_complete_games_played <- scores_complete_games %>%
  count(rule_idx) %>%
  mutate(n = n/2)

num_complete_games_played$n <- as.factor(num_complete_games_played$n)

ggplot(data=num_complete_games_played, aes(x=rule_idx, y=n)) +
  geom_bar(stat="identity") +
  labs(
    title = "Data Distribution of Complete Games",
    x = "Rule Index",
    y = "Number of Samples"
  )  +
  scale_y_discrete()
```


## Student Performance Vs. Teacher Performance 
```{r}
# Accuracies
complete_test_explorer <- scores_complete_games %>%
  filter(role == "explorer") %>%
  mutate(correct = hits + correct_rejections) %>%
  mutate(incorrect = misses + false_alarms) %>%
  select(gameid, rule_idx, correct, incorrect) %>%
  mutate(explorer_acc = correct / (correct + incorrect)) %>%
  mutate(rule_type = floor(rule_idx/10))

complete_test_student <- scores_complete_games %>%
  filter(role == "student") %>%
  mutate(correct = hits + correct_rejections) %>%
  mutate(incorrect = misses + false_alarms) %>%
  select(gameid, rule_idx, incorrect, correct) %>%
  mutate(student_acc = correct / (correct + incorrect)) %>%
  mutate(rule_type = floor(rule_idx/10))

complete_test_explorer_summary <- complete_test_explorer %>%
  group_by(rule_idx) %>%
  tidyboot_mean(column = explorer_acc) %>%
  rename(avg_explorer_acc = mean) %>%
  rename(explorer_ci_lower = ci_lower) %>%
  rename(explorer_ci_upper = ci_upper )%>%
  mutate(rule_type = floor(rule_idx/10))

complete_test_student_summary <- complete_test_student %>%
  group_by(rule_idx) %>%
  tidyboot_mean(column = student_acc) %>%
  rename(avg_student_acc = mean) %>%
  rename(student_ci_lower = ci_lower) %>%
  rename(student_ci_upper = ci_upper) %>%
  mutate(rule_type = floor(rule_idx/10))

complete_test <- bind_cols(complete_test_explorer, complete_test_student) %>%
    select(rule_idx, student_acc, explorer_acc, rule_type) 
complete_test$rule_idx <- as.factor(complete_test$rule_idx)
complete_test$rule_type <- as.factor(complete_test$rule_type)
complete_test <- complete_test %>%
  mutate(rule_type_text = fct_recode(rule_type,
    "Single Feature" = "0",
    "Conjunction" = "1",
    "Disjunction" = "2",
    "Conjunctive Disjunction" = "3",
    "Disjunctive Conjunction" = "4"
  ))

complete_test_summary <- bind_cols(complete_test_explorer_summary, complete_test_student_summary) %>% bind_cols(concept_summary) %>%
  select(rule_idx, avg_student_acc, avg_explorer_acc, student_ci_lower, student_ci_upper, explorer_ci_lower,  explorer_ci_upper, p_test_belongs_to_concept, phrase, kind, name, type, rule_type, chance_rate) %>%
  rename(student_acc = avg_student_acc) %>%
  rename(explorer_acc = avg_explorer_acc)   
complete_test_summary$rule_idx <- as.factor(complete_test_summary$rule_idx)
complete_test_summary$rule_type <- as.factor(complete_test_summary$rule_type)
complete_test_summary <- complete_test_summary %>%
  mutate(rule_type_text = fct_recode(rule_type,
    "Single Feature" = "0",
    "Conjunction" = "1",
    "Disjunction" = "2",
    "Conjunctive Disjunction" = "3",
    "Disjunctive Conjunction" = "4"
  ))

# Swap rows to make labeling cleaner

# Conjunction
x <- complete_test_summary[11:20,]
y <- x[1:8,]
z <- x[9:10,]
x[1:2,] = z
x[3:10,] = y
complete_test_summary[11:20,] = x

# Disjunction
x <- complete_test_summary[21:30,]
y <- x[1:6,]
z <- x[7:10,]
x[1:4,] = z
x[5:10,] = y
complete_test_summary[21:30,] = x


# Conjunctive Disjunction
x <- complete_test_summary[31:40,]
y <- x[1:4,]
z <- x[5:10,]
x[1:6,] = z
x[7:10,] = y
complete_test_summary[31:40,] = x


# Disjunctive Conjunction
x <- complete_test_summary[41:50,]
y <- x[1:2,]
z <- x[3:10,]
x[1:8,] = z
x[9:10,] = y
complete_test_summary[41:50,] = x

complete_test_summary <- complete_test_summary %>% mutate(id = row_number())
```

```{r}
# Individual Dyad Correlation 
cor.test(complete_test$student_acc, complete_test$explorer_acc)
```


```{r}
# Concept Type Accuracy Comparison
complete_type_summary <- scores_complete_games %>%
  mutate(
    correct = hits + correct_rejections,
    incorrect = misses + false_alarms,
    acc = correct / (correct + incorrect),
    rule_type = floor(rule_idx/10)
  ) %>%
  group_by(rule_type, role) %>%
  tidyboot_mean(column = acc)
complete_type_summary$rule_type <- as.factor(complete_type_summary$rule_type)
complete_type_summary <- complete_type_summary %>%
  mutate(rule_type_text = fct_recode(rule_type,
    "Single" = "0",
    "Conj." = "1",
    "Disj." = "2",
    "Conj. Disj." = "3",
    "Disj. Conj." = "4"
  ))
complete_type_summary$role <- as.factor(complete_type_summary$role)
complete_type_summary <- complete_type_summary %>%
  mutate(role = fct_recode(role,
    "Teacher" = "explorer",
    "Student" = "student"
  )) %>%
  rename(Role = role)

complete_type_summary$Role = factor(complete_type_summary$Role, levels = c("Teacher", "Student"))

```

```{r}
# Concept Type Average Accuracy
ggplot(
  complete_type_summary,
  aes(rule_type_text, alpha=Role, fill=rule_type_text, y=empirical_stat)
) + 
  geom_col(position='dodge', color="black") +  
  labs(
    x = "Rule",
    y = "Accuracy"
  ) + 
  geom_errorbar(aes(x=rule_type_text, ymin=ci_lower, ymax=ci_upper), color="black", width=0.5, position=position_dodge(.9), show.legend = FALSE) +
  theme_few() +
  theme(
    axis.text.x  = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title = element_text(size=15),
    legend.title = element_text(size=15),
    legend.text = element_text(size=10)
  ) +
  guides(color=FALSE) +
  guides(fill = guide_legend("Rule"), color=FALSE) +
  scale_alpha_manual(values = c("Teacher" = 1.0, "Student" = 0.2)) +
  

ggsave("./analyses/concept-type-accuracy.png", plot = last_plot(), width=5, height=3)
```


```{r fig.width=7, fig.height=4, echo=FALSE}
# Scatter Plot of Average Accuracies & Teacher-Student Pairs
ggplot(complete_test_summary
       , aes(x=student_acc, y=explorer_acc, fill=rule_type_text, label=rule_idx)) +
  geom_point(data = complete_test, size = 4, alpha=0.7, shape=21, show.legend=FALSE) +
  geom_point(size = 10, shape=21, color="black") +
  theme_few() +
  guides(fill = guide_legend("Rule"), color=FALSE) +
  labs(
    x = "Student Accuracy",
    y = "Teacher Acccuracy"
  ) +
  geom_abline(intercept = 0, slope = 1, linetype = 2) +
  geom_errorbar(aes(ymax = explorer_ci_lower, ymin = explorer_ci_upper), alpha=0.15) +
  geom_errorbarh(aes(xmax = student_ci_lower, xmin = student_ci_upper), alpha=0.15) +
  coord_fixed() +
  scale_x_continuous(limits = c(0.0, 1.0), breaks = c(0.25, 0.5, 0.75, 1.0)) +
  scale_y_continuous(limits = c(0.0, 1.0), breaks = c(0.25, 0.5, 0.75, 1.0)) +
  theme(
    axis.title = element_text(size=20),
    legend.title = element_text(size=25),
    legend.text = element_text(size=15),
    legend.position = c(0.7, 0.17),
    legend.background = element_rect(fill=alpha(0.1)),
    plot.title = element_blank()
  )

ggsave("./analyses/accuracy_scatter_plot.png", plot = last_plot(), width=9, height=9)
```
```{r fig.width=7, fig.height=4, echo=FALSE}
ggplot(complete_test_summary, aes(x=explorer_acc, xend=student_acc, y=reorder(id, desc(id)))) + 
  theme_few() +
  geom_dumbbell(
    size=0,
    size_x=4,
    size_xend = 4,
    colour_x="black",
    colour_xend = "gray", show.legend = T) +
    labs(
      x="Accuracy"
    ) +
  geom_segment(
    aes(
      color=rule_type_text,
      x=explorer_acc, 
      xend=student_acc, 
      y=reorder(id, desc(id)), 
      yend=reorder(id, desc(id))),
    size=2) +
  guides(color = guide_legend("Rule Type")) +
  geom_point(aes(x=chance_rate, y=reorder(id, desc(id)), shape=15), size=4, inherit.aes=F, show.legend = F, color="orange") +
  scale_shape_identity() + 
  scale_x_continuous(breaks = c(0.25, 0.5, 0.75, 1.0)) + 
  scale_y_discrete(labels = rev(c(
    "flowers: orange stems",
    "flowers: thorns present",
    "fish: white fangs",
    "fish: whiskers present",
    "bugs: orange head",
    "bugs: no wings",
    "birds: tail present",
    "birds: purple tail",
    "trees: purple berries",
    "trees: no leaves",

    "flowers: purple stem AND thorn",
    "flowers: orange petals AND purple center",
    "fish: white stripes AND whiskers  present",
    "fish: orange bodies AND purple stripe",
    "bugs: purple legs AND white head",
    "bugs: wings AND antennae present",
    "birds: purple wings AND crest present",
    "birds: orange wings AND tail present",
    "trees: orange trunk AND berries present",
    "trees: purple leaves AND berries present",

    "flowers: purple petals OR thorns present",
    "flowers: orange stems OR thorns present",
    "fish: orange bodies OR fangs present",
    "fish: white stripes OR whiskers present",
    "bugs: orange antennae OR wings present",
    "bugs: purple wings OR white legs",
    "birds: orange tail OR white wings",
    "birds: orange crest OR purple wings",
    "trees: purple berries OR white trunk",
    "trees: white leaves OR orange berries",

    "flowers: (purple stem AND white petals) OR orange center",
    "flowers: (thorns present AND purple petals) OR orange stem",
    "fish: (orange body AND purple stripes) OR whiskers present",
    "fish: (white body AND orange stripes) OR fangs present",
    "bugs: (purple legs AND white head) OR orange wings",
    "bugs: (white legs AND purple wings) OR orange antennae",
    "birds: (purple wings AND white crest) OR white tail",
    "birds: (purple crest AND purple tail) OR orange wings",
    "trees: (orange berries AND purple trunks) OR white leaves",
    "trees: (leaves present AND berries present) OR orange trunks",

    "flowers: (purple center OR orange stem) AND thorns present",
    "flowers: (purple stem OR thorns present) AND white center",
    "fish: (orange body OR fangs present) AND whiskers present",
    "fish: (white stripes OR purple body) AND whiskers present",
    "bugs: (antennae present OR wings present) AND purple body",
    "bugs: (white head OR orange antennae) AND purple legs",
    "birds: (orange tail OR white wings) AND orange crest",
    "birds: (white crest OR orange wings) AND tail present",
    "trees: (purple trunks OR white leaves) AND orange berries",
    "trees: (orange trunks OR berries present) AND white leaves"
  ))
) +
  coord_cartesian(xlim=c(0.45, 1.0)) +
  theme(
    axis.title = element_text(size=20),
    legend.title = element_text(size=25),
    legend.text = element_text(size=15),
    plot.title = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_text(size=15)
  )
ggsave("./analyses/accuracy_base_rate_plot.png", plot = last_plot(), width = 14, height = 8, dpi = 300 )
```

## Hamming Distance
```{r}
# Convert true/false to 1s and 0s
test_complete_games$turker_label <- as.logical(test_complete_games$turker_label)
test_complete_games$turker_label[test_complete_games$turker_label == "true"] <- 1
test_complete_games$turker_label[test_complete_games$turker_label == "false"] <- 0

complete_all_games_wide <- test_complete_games %>%
  select(role, stim_num, rule_idx, gameid, turker_label) %>%
  spread(role, turker_label) %>%
  mutate(rule_type = floor(rule_idx/10))

# Compute Hamming Distances for Concepts
hamming_distances <- complete_all_games_wide %>%
  group_by(rule_idx, gameid) %>%
  summarize(d = sum(explorer != student)) %>%
  mutate(rule_type = floor(rule_idx/10), Distribution="Empirical") 

hamming_distances$rule_idx <- as.factor(hamming_distances$rule_idx)
hamming_distances$rule_type <- as.factor(hamming_distances$rule_type)
hamming_distances <- hamming_distances %>%
    mutate(rule_type_text = 
           fct_recode(rule_type,
              "Single " = "0",
              "Conj." = "1",
              "Disj." = "2",
              "Conj. Disj." = "3",
              "Disj. Conj." = "4"
            )
    )

# Mean Hamming Distance of True Pairs
mean(hamming_distances$d)
```


```{r}
# Comparing teacher average accuracy vs. average hamming distance for concepts
comparison_acc_hd <- hamming_distances %>%
  group_by(rule_idx) %>%
  summarise(mean_d = mean(d)) %>%
  inner_join(complete_test_summary) %>%
  mutate(rule_type_text = 
           fct_recode(rule_type,
              "Single " = "0",
              "Conj." = "1",
              "Disj." = "2",
              "Conj. Disj." = "3",
              "Disj. Conj." = "4"
            )
    )

cor.test(comparison_acc_hd$explorer_acc, comparison_acc_hd$mean_d)

ggplot(comparison_acc_hd
       , aes(x=explorer_acc, y=mean_d, fill=rule_type_text)) +
  geom_point(size = 5, shape=21, color="black") +
  theme_few() +
  guides(fill = guide_legend("Rule"), color=FALSE) +
  labs(
    x = "Average Teacher Accuracy",
    y = "Average Hamming Distance"
  ) +
  theme(
    axis.title = element_text(size=15),
    legend.title = element_text(size=15),
    legend.text = element_text(size=10),
    plot.title = element_blank(),
    legend.position = c(0.85, 0.75),
    legend.background = element_rect(fill=alpha(0.1)),
  )
ggsave("./analyses/dist-by-acc.png", plot = last_plot(), width = 5, height = 4, dpi = 300 )
```

```{r}
# Compute 95 confidence interval and mean for dataframe of mean hamming distances
get_hd_stats<- function(x) {
  x <- x[order(-x$mean_d),]
  result <- list("lower_ci" = x[94, "mean_d"], "upper_ci" = x[6, "mean_d"], "mean"=mean(x$mean_d), x)
  return(result)
}

``` 

```{r}
# Permute teach-student pairs within a concept
# and take the overall mean hamming distance.
compute_average_intra_concept_shuffle_hd <- function() {
  df <- data.frame()
  for (i in 0:49) {
    x <- test_complete_games %>%
      filter(rule_idx == i) %>%
      group_by(role, gameid) %>%
      summarise(labels = paste(turker_label, collapse=", ")) %>%
      spread(role, labels)
    x$explorer <- sample(x$explorer)
    x <- x %>%
      mutate(
        explorer = strsplit(x$explorer, split = ","),
        student = strsplit(x$student, split = ","),
        d = 0
      ) 
    x$explorer = lapply(x$explorer, as.numeric)
    x$student = lapply(x$student, as.numeric)
    
    for (row in 1:nrow(x)) {
        x[row, "d"] = sum(x$explorer[[row]] != x$student[[row]])
    }
    df <- bind_rows(df, x)
  }
  result <- data.frame("Distribution"= "Intra-Concept Shuffled", "mean_d"=0)
  result$mean_d = mean(df$d)
  return (result)
}

concept_shuffled_hd <- data.frame()
for (i in 1:100) {
  concept_shuffled_hd <- bind_rows(concept_shuffled_hd, compute_average_intra_concept_shuffle_hd())
}


concept_shuffled_hd_stats <- get_hd_stats(concept_shuffled_hd)
View(concept_shuffled_hd_stats)
```

```{r}
# Permute teacher-student pairs across entire dataset
# and take the overall mean hamming distance.
compute_average_random_shuffle_hd <- function() {
  df <- data.frame()
  for (i in 0:49) {
    x <- test_complete_games %>%
      group_by(role, gameid, rule_idx) %>%
      summarise(labels = paste(turker_label, collapse=", ")) %>%
      spread(role, labels)
    
    x$explorer <- sample(x$explorer)
    x <- x %>%
      mutate(
        d = 0
      )
    x$explorer = strsplit(x$explorer, split = ",")
    x$student = strsplit(x$student, split = ",")
    x$explorer = lapply(x$explorer, as.numeric)
    x$student = lapply(x$student, as.numeric)
    
    for (row in 1:nrow(x)) {
        x[row, "d"] = sum(x$explorer[[row]] != x$student[[row]])
    }
    df <- bind_rows(df, x)
  }
  result <- data.frame("Distribution"= "Randomly Shuffled", "mean_d"=0)
  result$mean_d = mean(df$d)
  return (result)
}

random_shuffle_hd <- data.frame()
for (i in 1:100) {
  random_shuffle_hd <- bind_rows(random_shuffle_hd, compute_average_random_shuffle_hd())
  print(i)
}

random_shuffle_hd_stats <- get_hd_stats(random_shuffle_hd)
View(random_shuffle_hd_stats)
```

```{r}
# Permute teacher-student pairs across rules
# and take the overall mean hamming distance.
compute_average_rule_shuffle_hd <- function() {
  df <- data.frame()
  for (i in 0:4) {
    x <- test_complete_games %>%
      mutate(rule_type = floor(rule_idx/10)) %>%
      filter(rule_type == i) %>%
      group_by(role, gameid, rule_idx) %>%
      summarise(labels = paste(turker_label, collapse=", ")) %>%
      spread(role, labels)
    
    x$explorer <- sample(x$explorer)
    x <- x %>%
      mutate(
        d = 0
      )
    x$explorer = strsplit(x$explorer, split = ",")
    x$student = strsplit(x$student, split = ",")
    x$explorer = lapply(x$explorer, as.numeric)
    x$student = lapply(x$student, as.numeric)
    
    for (row in 1:nrow(x)) {
        x[row, "d"] = sum(x$explorer[[row]] != x$student[[row]])
    }
    df <- bind_rows(df, x)
  }
  result <- data.frame("Distribution"= "Intra-Rule Shuffled", "mean_d"=0)
  result$mean_d = mean(df$d)
  return (result)
}

rule_shuffle_hd <- data.frame()
for (i in 1:100) {
  rule_shuffle_hd <- bind_rows(rule_shuffle_hd, compute_average_rule_shuffle_hd())
  print(i)
}

rule_shuffle_hd_stats <- get_hd_stats(rule_shuffle_hd)
View(rule_shuffle_hd_stats)
```


## Language Analysis
```{r}
# Load Chat Messages
temp <- list.files(
    "../../../data/mp-game-6/complete_games/chatMessage",
  pattern="*.tsv",
  full.names=TRUE
)

msgs_complete_games <-do.call(rbind, lapply(temp, readr::read_tsv)) %>%
  group_by(gameid)
```

```{r}
msgs_complete_games$messageType <- as.factor(msgs_complete_games$messageType)
msgs_complete_games$uttClass <- as.factor(msgs_complete_games$uttClass)

msgs_complete_games <- msgs_complete_games %>% mutate(rule_type = floor(rule_idx/10))
msgs_complete_games$rule_type <- as.factor(msgs_complete_games$rule_type)


msgs_complete_games <- msgs_complete_games %>%  
  mutate(messageTypeText = fct_recode(messageType,
    "Confirmation" = "C",
    "Follow Up" = "F",
    "Informative" = "I",
    "Misc." = "M",
    "Social" = "S"
  )) %>%
  mutate(uttClassText = fct_recode(uttClass,
    "Generics" = "G",
    "Quantifiers" = "Q",
    "Adverbials" = "P",
    "Y/N" = "A",
    "Logic" = "L",
    "Either-Or" = "EO",
    "Conditionals" = "C",
    "Other" = "O",
    "Numerics" = "N",
    "Exemplars" = "E",
    "Imperatives" = "I",
    "Questions" = "?")) %>%
    mutate(rule_type_text = fct_recode(rule_type,
    "Single" = "0",
    "Conj." = "1",
    "Disj." = "2",
    "Conj. Disj." = "3",
    "Disj. Conj." = "4"
))

```

```{r}
ggplot(msgs_complete_games, aes(messageTypeText)) + 
  labs(
    x = "Message Type",
    y = "# of Messages"
  ) + geom_bar()
```

```{r}
explorer_msg_counts <- msgs_complete_games %>%
  filter(role == "explorer") %>% 
  subset(uttClassText != "NA")%>%
  subset(uttClassText != "Logic") %>%
  subset(uttClassText != "Either-Or") %>%  
  group_by(uttClassText) %>%
  tally() %>%
  transform(uttClassText = reorder(uttClassText, -n))

ggplot(explorer_msg_counts, aes(x = uttClassText, y = n)) + 
  labs(
    x = "",
    y = "# of Messages", 
    title = ""
  ) + geom_col() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size=15),
    axis.text.y = element_text(size=15),
    axis.title.y = element_text(size=18)
    )

ggsave("./analyses/teacher-langauge.png", plot = last_plot(), dpi = 300)
```

```{r}
explorer_msg_counts <- msgs_complete_games %>%
  filter(role == "explorer") %>% 
  subset(uttClassText != "NA")%>%
  group_by(uttClassText, rule_type_text) %>%
  tally() %>%
  transform(uttClassText = reorder(uttClassText, -n))

sum_explorer_msg_counts <- explorer_msg_counts %>%
  group_by(rule_type_text) %>%
  summarize(total = sum(n)) 

explorer_msg_counts_percentages <- explorer_msg_counts %>%
  inner_join(sum_explorer_msg_counts) %>%
  mutate(percentage = (n/total * 100))

ggplot(explorer_msg_counts_percentages, aes(x = uttClassText, y = percentage)) + 
  labs(
    x = "Language Type",
    y = "% of Messages", 
    title = "Teacher: Language Usage Across Informative & Follow-Up Messages"
  ) + geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + facet_wrap(~rule_type_text, 1)

ggsave("./analyses/teacher-langauge-facet.png", plot = last_plot(), dpi = 300)
```


```{r}
student_msg_counts <- msgs_complete_games %>%
  filter(role == "student") %>% 
  subset(uttClassText != "NA")%>%
  group_by(uttClassText) %>%
  tally() %>%
  transform(uttClassText = reorder(uttClassText, -n))

ggplot(student_msg_counts, aes(x = uttClassText, y = n)) + 
  labs(
    x = "Language Type",
    y = "# of Messages", 
    title = "Student: Language Usage Across Informative & Follow-Up Messages"
  ) + geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Timing Analysis -- Entire Chat Duration
```{r}
complete_games_avg_chat_times <- msgs_complete_games %>%
  group_by(gameid, rule_idx) %>%
  summarize(chatTime = sum(reactionTime)) %>%
  mutate(rule_type = floor(rule_idx/10)) %>%
  group_by(rule_type, rule_idx) %>%
  tidyboot_mean(col=chatTime) %>%
  mutate(Learning="Language")

complete_games_avg_train_times <- time_complete_games %>%
  filter(role == "explorer") %>%
  group_by(rule_idx) %>%
  tidyboot_mean(col=train) %>%
  mutate(Learning="Observation", rule_type = floor(rule_idx/10))

complete_games_avg_times <- complete_games_avg_chat_times %>%
  bind_rows(complete_games_avg_train_times)

complete_games_avg_times$rule_idx <- as.factor(complete_games_avg_times$rule_idx)
complete_games_avg_times$rule_type <- as.factor(complete_games_avg_times$rule_type)
complete_games_avg_times$Learning <- as.factor(complete_games_avg_times$Learning)


complete_games_avg_times <- complete_games_avg_times %>%
  mutate(rule_type_text = fct_recode(rule_type,
    "Single" = "0",
    "Conj." = "1",
    "Disj." = "2",
    "Conj. Disj." = "3",
    "Disj. Conj." = "4"
  )) %>%
  mutate(Learning = 
           factor(Learning, levels = c("Observation", "Language")
  ))
```

```{r}
ggplot() + 
geom_linerange(data=complete_games_avg_times, mapping=aes(x=Learning, ymin=ci_lower, ymax=ci_upper), width=0.2, size=1) + 
geom_point(data=complete_games_avg_times, mapping=aes(x=Learning, y=empirical_stat), size=4, shape=21, fill="white") +
theme_few() + 
facet_wrap(~rule_type_text, 1) +
  labs(
    title = "Time Analysis: Learning from Observation vs. Language (Entire Chat)",
    x = "Game Phase",
    y = "Time (Seconds)"
  )
```

## Timing Analysis -- Informative Chat Duration
```{r}
complete_games_avg_chat_times <- msgs_complete_games %>%
  filter(messageType == 'I' | messageType == 'F') %>%
  group_by(gameid, rule_idx) %>%
  summarize(chatTime = sum(reactionTime)) %>%
  mutate(rule_type = floor(rule_idx/10)) %>%
  group_by(rule_type, rule_idx) %>%
  tidyboot_mean(col=chatTime) %>%
  mutate(Learning="Language")

complete_games_avg_train_times <- time_complete_games %>%
  filter(role == "explorer") %>%
  group_by(rule_idx) %>%
  tidyboot_mean(col=train) %>%
  mutate(Learning="Observation", rule_type = floor(rule_idx/10))

complete_games_avg_times <- complete_games_avg_train_times %>%
  bind_rows(complete_games_avg_chat_times)

complete_games_avg_times$rule_idx <- as.factor(complete_games_avg_times$rule_idx)
complete_games_avg_times$rule_type <- as.factor(complete_games_avg_times$rule_type)
complete_games_avg_times$Learning <- as.factor(complete_games_avg_times$Learning)


complete_games_avg_times <- complete_games_avg_times %>%
  mutate(rule_type_text = fct_recode(rule_type,
    "Single" = "0",
    "Conj." = "1",
    "Disj." = "2",
    "Conj. Disj." = "3",
    "Disj. Conj." = "4"
  )) %>%
  mutate(Learning = 
           factor(Learning, levels = c("Observation", "Language")
  ))
```

```{r}
ggplot() + 
geom_errorbar(data=complete_games_avg_times, mapping=aes(x=Learning, ymin=ci_lower, ymax=ci_upper), size=0.2, width=0.2,
               position = position_dodge(width=2, preserve = "total")) +
geom_point(data=complete_games_avg_times, mapping=aes(x=Learning, y=empirical_stat), size=4, shape=21, fill="white") +
geom_line(data=complete_games_avg_times, aes(x=Learning, y=empirical_stat, group=rule_idx)) +
theme_few() + 
facet_wrap(~rule_type_text, 1) +
  labs(
    x = "",
    y = "Average Time (Seconds)" 
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("./analyses/time.png", plot = last_plot(), width = 5, height = 3, dpi = 300)
```

