---
title: "Critter Game - Data - Catch Trial"
author: "Lauren Oey"
date: "7/10/2017"
output: github_document
---

```{r preamble, tidy=TRUE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(data.table)
#library(xtable)
library(langcog)
library(forcats)


#setting the directory
setwd("../../../mturk/game-2/")


catch_trial_data <- read.csv("game-2-catch_trials.csv")

#View(catch_trial_data)

str(catch_trial_data)
summary(catch_trial_data)

catch_test <- subset(catch_trial_data, catch_trial_data$trial_type=="test_trial")
#catch_test$response <- grep(catch_test$response)

summary(catch_test$col1)




#catch_test_wug <- subset(catch_test, catch_test$species=="wug" & Correct == FALSE)

#wug.color = #4f9fda
#fep.color = #eec900
#lorch.color = #edc901 (yellow) or #dc74dc (purple)

purple <- c("#dc74dc","#dc74dd","#dd74dc","#dd74dd")

catch_test$Color <- ifelse(catch_test$species=="wug", "blue",
                           ifelse(catch_test$col1 %in% purple, "purple", "yellow"
  )
)

catch_test$Response.edit <- tolower(catch_test$response)


catch_test$Correct <- ifelse(
  catch_test$species==catch_test$Response.edit, TRUE, FALSE)

# compare correct species to incorrect input
catch_test_errors <- catch_test %>%
  filter(Correct == FALSE) %>%
  select(species, Response.edit)
#View(catch_test_errors)

catch_test$Response.cat <- ifelse(catch_test$Response.edit == "wug", "wug",
                                  ifelse(catch_test$Response.edit == "fep", "fep",
                                         ifelse(catch_test$Response.edit == "lorch", "lorch", "other")))

#data frame structure
# data.frame(
#   distribution = c( ... ),
#   question = c( ... ),
#   targetColor = c("blue", "yellow", "purple", "blue", ... ),
#   codedResponse = c("fep", "lorch", "other", "wug", ...) # only four categories: fep, lorch, wug, other
# )


catch_test_reduced <- catch_test %>%
  select(workerid, trial_num, species, question, distribution, response, Response.cat, Correct, Color)
#View(catch_test_reduced)
```


# Proportion Correct By Subject

```{r, results='asis'}
catch_test_reduced_by_subj <- catch_test_reduced %>%
  group_by(question, distribution) %>%
  mutate(Correct_trial = ifelse(Correct==TRUE, 1, 0)) %>%
  group_by(workerid, question, distribution) %>%
  summarise(Total_trials = sum(n()), Correct_trials = sum(Correct_trial)) %>%
  mutate(Percentage_correct = Correct_trials/Total_trials)

catch_test_reduced_by_subj

graph_by_subj <- ggplot(catch_test_reduced_by_subj, aes(x=workerid, y=Percentage_correct, colour=distribution, fill=distribution)) +
  geom_bar(stat="identity") +
  scale_x_discrete("Subjects") +
  scale_y_continuous("Percentage of Trials Correct") +
  scale_colour_discrete(guide=guide_legend("Distribution")) +
  scale_fill_discrete(guide=guide_legend("Distribution")) +
  #facet_wrap(~distribution) +
  ggtitle("Accuracy on Catch Trials by Subject") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5, size=18, face="bold"),
        strip.background = element_rect(fill="skyblue"),
        strip.text = element_text(size=12, face="bold"))
graph_by_subj

#ggsave("graph_by_subj.pdf")
```


# Proportion Correct By Species and Distribution

```{r, results='asis'}
catch_test_reduced_by_species_distr <- catch_test_reduced %>%
  group_by(species, distribution) %>%
  mutate(Correct_trial = ifelse(Correct==TRUE, 1, 0)) %>%
  summarise(Total_trials = sum(n()), Correct_trials = sum(Correct_trial)) %>%
  ungroup() %>%
  mutate(Percentage_correct = Correct_trials/Total_trials,
         species = factor(species, 
                               levels = c("wug", "fep", "lorch"),
                               labels = c("Wug", "Fep", "Lorch")
                               ))

catch_test_reduced_by_species_distr

graph_by_species_distr <- ggplot(catch_test_reduced_by_species_distr, aes(x=species, y=Percentage_correct)) +
  geom_bar(stat="identity") +
  scale_x_discrete("Species") +
  scale_y_continuous("Percentage of Trials Correct", limits=c(0,1)) +
  scale_colour_discrete(guide=guide_legend("Distribution")) +
  scale_fill_discrete(guide=guide_legend("Distribution")) +
  facet_wrap(~distribution) +
  ggtitle("Accuracy on Catch Trials by Species") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5, size=18, face="bold"),
        strip.background = element_rect(fill="skyblue"),
        strip.text = element_text(size=12, face="bold"))
graph_by_species_distr

#ggsave("Graph_by_Species.pdf")


```
# Proportion Correct By Species and Question

### Shouldn't affect anything

```{r, results='asis'}
catch_test_reduced_by_species_question <- catch_test_reduced %>%
  group_by(species, question) %>%
  mutate(Correct_trial = ifelse(Correct==TRUE, 1, 0)) %>%
  summarise(Total_trials = sum(n()), Correct_trials = sum(Correct_trial)) %>%
  ungroup() %>%
  mutate(Percentage_correct = Correct_trials/Total_trials,
         species = factor(species, 
                               levels = c("wug", "fep", "lorch"),
                               labels = c("Wug", "Fep", "Lorch")
                               ))

catch_test_reduced_by_species_question

graph_by_species_question <- ggplot(catch_test_reduced_by_species_question, aes(x=species, y=Percentage_correct)) +
  geom_bar(stat="identity") +
  scale_x_discrete("Species") +
  scale_y_continuous("Percentage of Trials Correct", limits=c(0,1)) +
  scale_colour_discrete(guide=guide_legend("Question")) +
  scale_fill_discrete(guide=guide_legend("Question")) +
  facet_wrap(~question) +
  ggtitle("Accuracy on Catch Trials by Species") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5, size=18, face="bold"),
        strip.background = element_rect(fill="skyblue"),
        strip.text = element_text(size=12, face="bold"))
graph_by_species_question

#ggsave("Graph_by_Species.pdf")


```

# Proportion of Species by Color

```{r, results='asis'}
catch_test_reduced_species_by_color <- catch_test_reduced %>%
  group_by(Response.cat, Color) %>%
  summarise(Total_trials = sum(n())) %>%
  ungroup() %>%
  mutate(Response.cat = factor(Response.cat, 
                               levels = c("wug", "fep", "lorch", "other"),
                               labels = c("Wug", "Fep", "Lorch", "Other")
                               ))


catch_test_reduced_species_by_color

graph_species_by_color_count <- ggplot(catch_test_reduced_species_by_color, aes(x=Response.cat, y=Total_trials, fill=Color)) +
  geom_bar(stat="identity") +
  scale_x_discrete("Species Stated in Response") +
  scale_y_continuous("Count") +
  scale_fill_manual(values = c("blue", "purple", "yellow"))+
  #scale_colour_discrete(guide=guide_legend("Distribution")) +
  #scale_fill_discrete(guide=guide_legend("Distribution")) +
  facet_wrap(~Color) +
  ggtitle("Species Responses on Test Trials by Stimuli Responses") +
  guides(fill=FALSE) +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5, size=18, face="bold"),
        strip.background = element_rect(fill="skyblue"),
        strip.text = element_text(size=12, face="bold"))
graph_species_by_color_count

#ggsave("Graph_Species_by_Color_count.pdf")


catch_test_reduced_species_by_color_prop <- catch_test_reduced %>%
  group_by(Response.cat, Color) %>%
  summarise(Total_trials = n()) %>%
  group_by(Color) %>%
  mutate(All_Color_trials = sum(Total_trials),
         Percent_trials = Total_trials/All_Color_trials) %>%
  ungroup() %>%
  mutate(Response.cat = factor(Response.cat, 
                               levels = c("wug", "fep", "lorch", "other"),
                               labels = c("Wug", "Fep", "Lorch", "Other")
                               ))

#sanity check
#catch_test_reduced_species_by_color_prop %>%
#  group_by(Color) %>%
#  summarise(sum(Percent_trials))

data_summary <- summarySE(graph_species_by_color_prop, measurevar="Percent_trials", groupvars=c("Response.cat","question","distribution"))
data_summary

graph_species_by_color_prop <- ggplot(catch_test_reduced_species_by_color_prop, aes(x=Response.cat, y=Percent_trials, fill = Color)) +
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=Percent_trials-ci, ymax=Percent_trials+ci),
                  width=.2,                    # Width of the error bars
                  position=position_dodge(.9)) +
  scale_x_discrete("Species Stated in Response") +
  scale_y_continuous("Percent", limits=c(0,1)) +
  #scale_colour_discrete(guide=guide_legend("Distribution")) +
  #scale_fill_discrete(guide=guide_legend("Distribution")) +
  facet_wrap(~Color) +
  scale_fill_manual(values = c("blue", "purple", "yellow"))+
  ggtitle("Species Responses on Test Trials by Stimuli Responses") +
  guides(fill=FALSE) +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5, size=18, face="bold"),
        strip.background = element_rect(fill=c("skyblue")),
        strip.text = element_text(size=12, face="bold"))
graph_species_by_color_prop

#ggsave("Graph_Species_by_Color_prop.pdf")

```





